version: '3.8'
services:
  nginx:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes:
      - .:/var/www/html
    networks:
      - otea-net
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - .:/var/www/html
    networks:
      - otea-net
  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    volumes:
      - .:/app
    networks:
      - otea-net
networks:
  otea-net:
    driver: bridge
